// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'services/config_service.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: ConfigService.firebaseBrowserApiKey,
    appId: ConfigService.firebaseAppId,
    messagingSenderId: ConfigService.firebaseMessagingSenderId,
    projectId: ConfigService.firebaseProjectId,
    authDomain: '${ConfigService.firebaseProjectId}.firebaseapp.com',
    storageBucket: ConfigService.firebaseStorageBucket,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: ConfigService.firebaseAndroidApiKey,
    appId: ConfigService.firebaseAppId,
    messagingSenderId: ConfigService.firebaseMessagingSenderId,
    projectId: ConfigService.firebaseProjectId,
    storageBucket: ConfigService.firebaseStorageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: ConfigService.firebaseIosApiKey,
    appId: ConfigService.firebaseAppId,
    messagingSenderId: ConfigService.firebaseMessagingSenderId,
    projectId: ConfigService.firebaseProjectId,
    storageBucket: ConfigService.firebaseStorageBucket,
    androidClientId: ConfigService.firebaseAndroidClientId,
    iosClientId: ConfigService.firebaseIosClientId,
    iosBundleId: ConfigService.firebaseIosBundleId,
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: ConfigService.firebaseIosApiKey,
    appId: ConfigService.firebaseAppId,
    messagingSenderId: ConfigService.firebaseMessagingSenderId,
    projectId: ConfigService.firebaseProjectId,
    storageBucket: ConfigService.firebaseStorageBucket,
    androidClientId: ConfigService.firebaseAndroidClientId,
    iosClientId: ConfigService.firebaseIosClientId,
    iosBundleId: ConfigService.firebaseIosBundleId,
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: ConfigService.firebaseBrowserApiKey,
    appId: ConfigService.firebaseAppId,
    messagingSenderId: ConfigService.firebaseMessagingSenderId,
    projectId: ConfigService.firebaseProjectId,
    authDomain: '${ConfigService.firebaseProjectId}.firebaseapp.com',
    storageBucket: ConfigService.firebaseStorageBucket,
  );
}
