// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6B6uFnMJFUQiuC-afTk_h5vpCKbAHsBY',
    appId: '1:542669278565:web:12e13eeed16385d1a1a58c',
    messagingSenderId: '542669278565',
    projectId: 'spoonfeed-78597',
    authDomain: 'spoonfeed-78597.firebaseapp.com',
    storageBucket: 'spoonfeed-78597.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxqVG28gtZ525t_E_NXajG5NVhQGtAD5A',
    appId: '1:542669278565:android:1ce70b1f57d82979a1a58c',
    messagingSenderId: '542669278565',
    projectId: 'spoonfeed-78597',
    storageBucket: 'spoonfeed-78597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB999iHXdG0u7MnESi14qTUcAnFLVTRsXk',
    appId: '1:542669278565:ios:20e2f333cbab248aa1a58c',
    messagingSenderId: '542669278565',
    projectId: 'spoonfeed-78597',
    storageBucket: 'spoonfeed-78597.firebasestorage.app',
    androidClientId: '542669278565-f8ckecu47rjvudronhe4kvgulpkgtuo2.apps.googleusercontent.com',
    iosClientId: '542669278565-nehn276q4ileaqta2imlrlonbb8d63dc.apps.googleusercontent.com',
    iosBundleId: 'com.reelai.spoonfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB999iHXdG0u7MnESi14qTUcAnFLVTRsXk',
    appId: '1:542669278565:ios:20e2f333cbab248aa1a58c',
    messagingSenderId: '542669278565',
    projectId: 'spoonfeed-78597',
    storageBucket: 'spoonfeed-78597.firebasestorage.app',
    androidClientId: '542669278565-f8ckecu47rjvudronhe4kvgulpkgtuo2.apps.googleusercontent.com',
    iosClientId: '542669278565-nehn276q4ileaqta2imlrlonbb8d63dc.apps.googleusercontent.com',
    iosBundleId: 'com.reelai.spoonfeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6B6uFnMJFUQiuC-afTk_h5vpCKbAHsBY',
    appId: '1:542669278565:web:78ed8625c24ba59aa1a58c',
    messagingSenderId: '542669278565',
    projectId: 'spoonfeed-78597',
    authDomain: 'spoonfeed-78597.firebaseapp.com',
    storageBucket: 'spoonfeed-78597.firebasestorage.app',
  );
}
